/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package androidx.constraintlayout.coremp.utils

import kotlin.test.Test
import kotlin.test.assertEquals

class GridEngineTest {
    @Test
    fun testNoArgument() {
        val engine = GridEngine()
        engine.setRows(3)
        engine.setColumns(3)
        engine.setNumWidgets(5)
        engine.setup()
        assertEquals(0, engine.leftOfWidget(0))
        assertEquals(0, engine.topOfWidget(0))
        assertEquals(0, engine.rightOfWidget(0))
        assertEquals(0, engine.bottomOfWidget(0))
        assertEquals(1, engine.leftOfWidget(1))
        assertEquals(0, engine.topOfWidget(1))
        assertEquals(1, engine.rightOfWidget(1))
        assertEquals(0, engine.bottomOfWidget(1))
        assertEquals(2, engine.leftOfWidget(2))
        assertEquals(0, engine.topOfWidget(2))
        assertEquals(2, engine.rightOfWidget(2))
        assertEquals(0, engine.bottomOfWidget(2))
        assertEquals(0, engine.leftOfWidget(3))
        assertEquals(1, engine.topOfWidget(3))
        assertEquals(0, engine.rightOfWidget(3))
        assertEquals(1, engine.bottomOfWidget(3))
        assertEquals(1, engine.leftOfWidget(4))
        assertEquals(1, engine.topOfWidget(4))
        assertEquals(1, engine.rightOfWidget(4))
        assertEquals(1, engine.bottomOfWidget(4))
    }

    @Test
    fun testSimpleEngineHorizontal() {
        val engine = GridEngine(3, 3, 5)
        assertEquals(0, engine.leftOfWidget(0))
        assertEquals(0, engine.topOfWidget(0))
        assertEquals(0, engine.rightOfWidget(0))
        assertEquals(0, engine.bottomOfWidget(0))
        assertEquals(1, engine.leftOfWidget(1))
        assertEquals(0, engine.topOfWidget(1))
        assertEquals(1, engine.rightOfWidget(1))
        assertEquals(0, engine.bottomOfWidget(1))
        assertEquals(2, engine.leftOfWidget(2))
        assertEquals(0, engine.topOfWidget(2))
        assertEquals(2, engine.rightOfWidget(2))
        assertEquals(0, engine.bottomOfWidget(2))
        assertEquals(0, engine.leftOfWidget(3))
        assertEquals(1, engine.topOfWidget(3))
        assertEquals(0, engine.rightOfWidget(3))
        assertEquals(1, engine.bottomOfWidget(3))
        assertEquals(1, engine.leftOfWidget(4))
        assertEquals(1, engine.topOfWidget(4))
        assertEquals(1, engine.rightOfWidget(4))
        assertEquals(1, engine.bottomOfWidget(4))
    }

    @Test
    fun testSimpleEngineVertical() {
        // Grid engine with 3 rows, 3 columns, and 5 widgets
        val engine = GridEngine(3, 3, 5)
        // Set the orientation to Vertical
        engine.setOrientation(1)
        engine.setup()
        assertEquals(0, engine.leftOfWidget(0))
        assertEquals(0, engine.topOfWidget(0))
        assertEquals(0, engine.rightOfWidget(0))
        assertEquals(0, engine.bottomOfWidget(0))
        assertEquals(0, engine.leftOfWidget(1))
        assertEquals(1, engine.topOfWidget(1))
        assertEquals(0, engine.rightOfWidget(1))
        assertEquals(1, engine.bottomOfWidget(1))
        assertEquals(0, engine.leftOfWidget(2))
        assertEquals(2, engine.topOfWidget(2))
        assertEquals(0, engine.rightOfWidget(2))
        assertEquals(2, engine.bottomOfWidget(2))
        assertEquals(1, engine.leftOfWidget(3))
        assertEquals(0, engine.topOfWidget(3))
        assertEquals(1, engine.rightOfWidget(3))
        assertEquals(0, engine.bottomOfWidget(3))
        assertEquals(1, engine.leftOfWidget(4))
        assertEquals(1, engine.topOfWidget(4))
        assertEquals(1, engine.rightOfWidget(4))
        assertEquals(1, engine.bottomOfWidget(4))
    }

    @Test
    fun testSpansSkipsHorizontal() {
        val engine = GridEngine(4, 4, 5)
        engine.setSkips("0:2x2,6:1x1")
        engine.setSpans("12:1x3")
        engine.setup()
        assertEquals(0, engine.leftOfWidget(0))
        assertEquals(3, engine.topOfWidget(0))
        assertEquals(2, engine.rightOfWidget(0))
        assertEquals(3, engine.bottomOfWidget(0))
        assertEquals(2, engine.leftOfWidget(1))
        assertEquals(0, engine.topOfWidget(1))
        assertEquals(2, engine.rightOfWidget(1))
        assertEquals(0, engine.bottomOfWidget(1))
        assertEquals(3, engine.leftOfWidget(2))
        assertEquals(0, engine.topOfWidget(2))
        assertEquals(3, engine.rightOfWidget(2))
        assertEquals(0, engine.bottomOfWidget(2))
        assertEquals(3, engine.leftOfWidget(3))
        assertEquals(1, engine.topOfWidget(3))
        assertEquals(3, engine.rightOfWidget(3))
        assertEquals(1, engine.bottomOfWidget(3))
        assertEquals(0, engine.leftOfWidget(4))
        assertEquals(2, engine.topOfWidget(4))
        assertEquals(0, engine.rightOfWidget(4))
        assertEquals(2, engine.bottomOfWidget(4))
    }

    @Test
    fun testSpansSkipsVertical() {
        val engine = GridEngine(4, 4, 5)
        engine.setOrientation(1)
        engine.setSkips("0:2x2,6:2x1")
        engine.setSpans("12:3x1")
        engine.setup()
        assertEquals(3, engine.leftOfWidget(0))
        assertEquals(0, engine.topOfWidget(0))
        assertEquals(3, engine.rightOfWidget(0))
        assertEquals(2, engine.bottomOfWidget(0))
        assertEquals(0, engine.leftOfWidget(1))
        assertEquals(2, engine.topOfWidget(1))
        assertEquals(0, engine.rightOfWidget(1))
        assertEquals(2, engine.bottomOfWidget(1))
        assertEquals(0, engine.leftOfWidget(2))
        assertEquals(3, engine.topOfWidget(2))
        assertEquals(0, engine.rightOfWidget(2))
        assertEquals(3, engine.bottomOfWidget(2))
        assertEquals(2, engine.leftOfWidget(3))
        assertEquals(0, engine.topOfWidget(3))
        assertEquals(2, engine.rightOfWidget(3))
        assertEquals(0, engine.bottomOfWidget(3))
        assertEquals(2, engine.leftOfWidget(4))
        assertEquals(1, engine.topOfWidget(4))
        assertEquals(2, engine.rightOfWidget(4))
        assertEquals(1, engine.bottomOfWidget(4))
    }

    @Test
    fun testSetRows() {
        val engine = GridEngine(4, 4, 5)
        engine.setRows(3)
        engine.setup()
        assertEquals(0, engine.leftOfWidget(0))
        assertEquals(0, engine.topOfWidget(0))
        assertEquals(0, engine.rightOfWidget(0))
        assertEquals(0, engine.bottomOfWidget(0))
        assertEquals(1, engine.leftOfWidget(1))
        assertEquals(0, engine.topOfWidget(1))
        assertEquals(1, engine.rightOfWidget(1))
        assertEquals(0, engine.bottomOfWidget(1))
        assertEquals(2, engine.leftOfWidget(2))
        assertEquals(0, engine.topOfWidget(2))
        assertEquals(2, engine.rightOfWidget(2))
        assertEquals(0, engine.bottomOfWidget(2))
        assertEquals(3, engine.leftOfWidget(3))
        assertEquals(0, engine.topOfWidget(3))
        assertEquals(3, engine.rightOfWidget(3))
        assertEquals(0, engine.bottomOfWidget(3))
        assertEquals(0, engine.leftOfWidget(4))
        assertEquals(1, engine.topOfWidget(4))
        assertEquals(0, engine.rightOfWidget(4))
        assertEquals(1, engine.bottomOfWidget(4))
    }

    @Test
    fun testSetColumns() {
        val engine = GridEngine(4, 4, 5)
        engine.setColumns(3)
        engine.setup()
        assertEquals(0, engine.leftOfWidget(0))
        assertEquals(0, engine.topOfWidget(0))
        assertEquals(0, engine.rightOfWidget(0))
        assertEquals(0, engine.bottomOfWidget(0))
        assertEquals(1, engine.leftOfWidget(1))
        assertEquals(0, engine.topOfWidget(1))
        assertEquals(1, engine.rightOfWidget(1))
        assertEquals(0, engine.bottomOfWidget(1))
        assertEquals(2, engine.leftOfWidget(2))
        assertEquals(0, engine.topOfWidget(2))
        assertEquals(2, engine.rightOfWidget(2))
        assertEquals(0, engine.bottomOfWidget(2))
        assertEquals(0, engine.leftOfWidget(3))
        assertEquals(1, engine.topOfWidget(3))
        assertEquals(0, engine.rightOfWidget(3))
        assertEquals(1, engine.bottomOfWidget(3))
        assertEquals(1, engine.leftOfWidget(4))
        assertEquals(1, engine.topOfWidget(4))
        assertEquals(1, engine.rightOfWidget(4))
        assertEquals(1, engine.bottomOfWidget(4))
    }

    @Test
    fun testSetNumWidgets() {
        val engine = GridEngine(3, 3)
        engine.setNumWidgets(5)
        engine.setup()
        assertEquals(0, engine.leftOfWidget(0))
        assertEquals(0, engine.topOfWidget(0))
        assertEquals(0, engine.rightOfWidget(0))
        assertEquals(0, engine.bottomOfWidget(0))
        assertEquals(1, engine.leftOfWidget(1))
        assertEquals(0, engine.topOfWidget(1))
        assertEquals(1, engine.rightOfWidget(1))
        assertEquals(0, engine.bottomOfWidget(1))
        assertEquals(2, engine.leftOfWidget(2))
        assertEquals(0, engine.topOfWidget(2))
        assertEquals(2, engine.rightOfWidget(2))
        assertEquals(0, engine.bottomOfWidget(2))
        assertEquals(0, engine.leftOfWidget(3))
        assertEquals(1, engine.topOfWidget(3))
        assertEquals(0, engine.rightOfWidget(3))
        assertEquals(1, engine.bottomOfWidget(3))
        assertEquals(1, engine.leftOfWidget(4))
        assertEquals(1, engine.topOfWidget(4))
        assertEquals(1, engine.rightOfWidget(4))
        assertEquals(1, engine.bottomOfWidget(4))
    }

    @Test
    fun testToggleSkips() {
        val engine = GridEngine(4, 4, 5)
        engine.setSkips("0:2x2,6:1x1")
        engine.setup()
        assertEquals(2, engine.leftOfWidget(0))
        assertEquals(0, engine.topOfWidget(0))
        assertEquals(2, engine.rightOfWidget(0))
        assertEquals(0, engine.bottomOfWidget(0))
        assertEquals(3, engine.leftOfWidget(1))
        assertEquals(0, engine.topOfWidget(1))
        assertEquals(3, engine.rightOfWidget(1))
        assertEquals(0, engine.bottomOfWidget(1))
        assertEquals(3, engine.leftOfWidget(2))
        assertEquals(1, engine.topOfWidget(2))
        assertEquals(3, engine.rightOfWidget(2))
        assertEquals(1, engine.bottomOfWidget(2))
        assertEquals(0, engine.leftOfWidget(3))
        assertEquals(2, engine.topOfWidget(3))
        assertEquals(0, engine.rightOfWidget(3))
        assertEquals(2, engine.bottomOfWidget(3))
        assertEquals(1, engine.leftOfWidget(4))
        assertEquals(2, engine.topOfWidget(4))
        assertEquals(1, engine.rightOfWidget(4))
        assertEquals(2, engine.bottomOfWidget(4))
        engine.setSkips("")
        engine.setup()
        assertEquals(0, engine.leftOfWidget(0))
        assertEquals(0, engine.topOfWidget(0))
        assertEquals(0, engine.rightOfWidget(0))
        assertEquals(0, engine.bottomOfWidget(0))
        assertEquals(1, engine.leftOfWidget(1))
        assertEquals(0, engine.topOfWidget(1))
        assertEquals(1, engine.rightOfWidget(1))
        assertEquals(0, engine.bottomOfWidget(1))
        assertEquals(2, engine.leftOfWidget(2))
        assertEquals(0, engine.topOfWidget(2))
        assertEquals(2, engine.rightOfWidget(2))
        assertEquals(0, engine.bottomOfWidget(2))
        assertEquals(3, engine.leftOfWidget(3))
        assertEquals(0, engine.topOfWidget(3))
        assertEquals(3, engine.rightOfWidget(3))
        assertEquals(0, engine.bottomOfWidget(3))
        assertEquals(0, engine.leftOfWidget(4))
        assertEquals(1, engine.topOfWidget(4))
        assertEquals(0, engine.rightOfWidget(4))
        assertEquals(1, engine.bottomOfWidget(4))
    }

    @Test
    fun testToggleSpans() {
        val engine = GridEngine(4, 4, 5)
        engine.setSpans("0:2x2,3:2x1")
        engine.setup()
        assertEquals(0, engine.leftOfWidget(0))
        assertEquals(0, engine.topOfWidget(0))
        assertEquals(1, engine.rightOfWidget(0))
        assertEquals(1, engine.bottomOfWidget(0))
        assertEquals(3, engine.leftOfWidget(1))
        assertEquals(0, engine.topOfWidget(1))
        assertEquals(3, engine.rightOfWidget(1))
        assertEquals(1, engine.bottomOfWidget(1))
        assertEquals(2, engine.leftOfWidget(2))
        assertEquals(0, engine.topOfWidget(2))
        assertEquals(2, engine.rightOfWidget(2))
        assertEquals(0, engine.bottomOfWidget(2))
        assertEquals(2, engine.leftOfWidget(3))
        assertEquals(1, engine.topOfWidget(3))
        assertEquals(2, engine.rightOfWidget(3))
        assertEquals(1, engine.bottomOfWidget(3))
        assertEquals(0, engine.leftOfWidget(4))
        assertEquals(2, engine.topOfWidget(4))
        assertEquals(0, engine.rightOfWidget(4))
        assertEquals(2, engine.bottomOfWidget(4))
        engine.setSpans("")
        engine.setup()
        assertEquals(0, engine.leftOfWidget(0))
        assertEquals(0, engine.topOfWidget(0))
        assertEquals(0, engine.rightOfWidget(0))
        assertEquals(0, engine.bottomOfWidget(0))
        assertEquals(1, engine.leftOfWidget(1))
        assertEquals(0, engine.topOfWidget(1))
        assertEquals(1, engine.rightOfWidget(1))
        assertEquals(0, engine.bottomOfWidget(1))
        assertEquals(2, engine.leftOfWidget(2))
        assertEquals(0, engine.topOfWidget(2))
        assertEquals(2, engine.rightOfWidget(2))
        assertEquals(0, engine.bottomOfWidget(2))
        assertEquals(3, engine.leftOfWidget(3))
        assertEquals(0, engine.topOfWidget(3))
        assertEquals(3, engine.rightOfWidget(3))
        assertEquals(0, engine.bottomOfWidget(3))
        assertEquals(0, engine.leftOfWidget(4))
        assertEquals(1, engine.topOfWidget(4))
        assertEquals(0, engine.rightOfWidget(4))
        assertEquals(1, engine.bottomOfWidget(4))
    }
}
