name: CI Assemble, Test, and Publish

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-home-cache-cleanup: true
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew :sample:assemble
      - name: Test
        run: ./gradlew desktopTest
      - name: Deploy to Sonatype
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew publishAllPublicationsToSonatypeRepository
        env:
          OSSRH_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.GPG_KEY }}
          SIGNING_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-reports
          path: |
            **/build/reports/*

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-test-results
          path: |
            **/build/test-results/*
